
"""Enterprise-grade Streamlit dashboard for the clickstream big-data project.

- MongoDB connection (local): mongodb://localhost:27017/
- Database: analytics_db
- Collections:
  1) user_session_metrics
  2) conversion_funnel_metrics
  3) trending_products

- i18n: English / Hindi / Gujarati (sidebar toggle; full UI updates dynamically)
- Robust schema mismatch handling:
  - Before rendering charts, if expected columns are missing, display:
    * missing column list
    * columns present list
    * df.head(1) preview

- Professional dashboard layout:
  - Corporate dark styling
  - Sidebar KPIs moved to sidebar
  - st.tabs() layout
  - Plotly dark-friendly formatting + clean visuals

Run:
    streamlit run app.py
"""

from __future__ import annotations

import datetime as dt
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import plotly.express as px
import streamlit as st
from plotly.graph_objs._figure import Figure
from pymongo import MongoClient


# -----------------------------
# Streamlit page config
# -----------------------------

st.set_page_config(
    page_title="Clickstream Analytics Dashboard",
    page_icon="📈",
    layout="wide",
)

# Expose hints for global/shared access.
# Actual sharing is controlled by Streamlit run flags / networking,
# but we set safe defaults in UI and documentation below.
ST_GLOBAL_NOTE = """To share this dashboard publicly (global link), use Streamlit Community Cloud or a tunneling tool (e.g., ngrok)."""



# -----------------------------
# i18n
# -----------------------------

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "language_label": "Language",
        "about": "This dashboard visualizes aggregated clickstream insights generated by your PySpark pipeline and stored in MongoDB.",

        "app_name": "Clickstream Analytics Dashboard",
        "subtitle": "MongoDB-backed insights from your PySpark pipeline",

        "sidebar_kpis": "High-Level KPIs",
        "kpi_users": "Total Users",
        "kpi_actions": "Total Actions",
        "kpi_db": "MongoDB",
        "kpi_last_refresh": "Last Refreshed",

        "about_section": "About this Dashboard",

        "visual_analytics": "Visual Analytics",
        "raw_data_explorer": "Raw Data Explorer",

        "section_funnel": "Conversion Funnel",
        "section_trending": "Trending Products",

        "funnel_title": "View → Cart → Purchase",
        "trending_title": "Top 10 Trending Products",

        "funnel_view": "Views",
        "funnel_cart": "Cart",
        "funnel_purchase": "Purchases",

        "trending_x": "Count",
        "trending_y": "Product",

        "table_title": "Raw Data (Trending Products - Top 10)",

        "empty_warning_run_pipeline": "No data found in MongoDB collections. Please run the PySpark pipeline first.",
        "mongo_status_connected": "Connected to MongoDB",
        "mongo_status_disconnected": "Could not connect to MongoDB at mongodb://localhost:27017/.",

        "error_expected_columns_missing": "Expected columns missing. Showing a preview below to help you verify schema.",

        "refresh_button": "Refresh data",
        "columns_debug_title": "Schema Preview (for debugging column names)",
    },
    "hi": {
        "language_label": "भाषा",
        "about": "यह डैशबोर्ड आपके PySpark पाइपलाइन द्वारा बनाई गई और MongoDB में स्टोर की गई aggregated clickstream insights को दिखाता है।",

        "app_name": "क्लिकस्ट्रीम एनालिटिक्स डैशबोर्ड",
        "subtitle": "आपकी PySpark पाइपलाइन से MongoDB आधारित इनसाइट्स",

        "sidebar_kpis": "हाई-लेवल KPI",
        "kpi_users": "कुल उपयोगकर्ता",
        "kpi_actions": "कुल गतिविधियाँ",
        "kpi_db": "MongoDB",
        "kpi_last_refresh": "अंतिम रिफ्रेश",

        "about_section": "डैशबोर्ड के बारे में",

        "visual_analytics": "विजुअल एनालिटिक्स",
        "raw_data_explorer": "रॉ डेटा एक्सप्लोरर",

        "section_funnel": "कन्वर्ज़न फ़नल",
        "section_trending": "ट्रेंडिंग प्रोडक्ट्स",

        "funnel_title": "देखें → कार्ट → खरीदें",
        "trending_title": "शीर्ष 10 ट्रेंडिंग प्रोडक्ट्स",

        "funnel_view": "व्यूज़",
        "funnel_cart": "कार्ट",
        "funnel_purchase": "खरीदारी",

        "trending_x": "गणना",
        "trending_y": "प्रोडक्ट",

        "table_title": "कच्चा डेटा (ट्रेंडिंग प्रोडक्ट्स - टॉप 10)",

        "empty_warning_run_pipeline": "MongoDB कलेक्शनों में डेटा नहीं मिला। कृपया पहले PySpark पाइपलाइन चलाएँ।",
        "mongo_status_connected": "MongoDB से कनेक्ट हो गया",
        "mongo_status_disconnected": "mongodb://localhost:27017/ पर MongoDB से कनेक्ट नहीं हो पाया।",

        "error_expected_columns_missing": "अपेक्षित कॉलम नहीं मिले। कॉलम नाम जाँचने के लिए नीचे schema preview दिखाया जा रहा है।",

        "refresh_button": "डेटा रिफ्रेश करें",
        "columns_debug_title": "स्कीमा प्रीव्यू (डिबगिंग के लिए)",
    },
    "gu": {
        "language_label": "ભાષા",
        "about": "આ ડેશબોર્ડ તમારા PySpark પાઈપલાઈન દ્વારા બનાવેલ અને MongoDBમાં સંગ્રહિત aggregated clickstream insights દર્શાવે છે।",

        "app_name": "ક્લિકસ્ટ્રીમ એનાલિટિક્સ ડેશબોર્ડ",
        "subtitle": "તમારી PySpark પાઈપલાઈનમાંથી MongoDB આધારિત ઈન્સાઈટ્સ",

        "sidebar_kpis": "હાઈ-લેવલ KPI",
        "kpi_users": "કુલ વપરાશકર્તાઓ",
        "kpi_actions": "કુલ એક્શન",
        "kpi_db": "MongoDB",
        "kpi_last_refresh": "છેલ્લું રિફ્રેશ",

        "about_section": "ડેશબોર્ડ વિશે",

        "visual_analytics": "વિઝ્યુઅલ એનાલિટિક્સ",
        "raw_data_explorer": "રૉ ડેટા એક્સપ્લોરર",

        "section_funnel": "કન્વર્જન ફનલ",
        "section_trending": "ટ્રેન્ડિંગ પ્રોડક્ટ્સ",

        "funnel_title": "વ્યૂ → કાર્ટ → ખરીદી",
        "trending_title": "ટોપ 10 ટ્રેન્ડિંગ પ્રોડક્ટ્સ",

        "funnel_view": "વ્યુઝ",
        "funnel_cart": "કાર્ટ",
        "funnel_purchase": "ખરીદીઓ",

        "trending_x": "ગણતરી",
        "trending_y": "પ્રોડક્ટ",

        "table_title": "કાચો ડેટા (ટ્રેન્ડિંગ પ્રોડક્ટ્સ - ટોપ 10)",

        "empty_warning_run_pipeline": "MongoDB કલેક્શનમાં ડેટા મળ્યો નથી. કૃપા કરીને પહેલા PySpark પાઈપલાઈન ચલાવો।",
        "mongo_status_connected": "MongoDB સાથે જોડાણ થયું",
        "mongo_status_disconnected": "mongodb://localhost:27017/ પર MongoDB સાથે જોડાણ થઈ શક્યું નથી।",

        "error_expected_columns_missing": "અપેક્ષિત કોલમ મળ્યા નથી। કોલમ નામ તપાસવા માટે schema preview બતાવવામાં આવશે।",

        "refresh_button": "ડેટા રિફ્રેશ કરો",
        "columns_debug_title": "સ્કીમા પ્રિવ્યુ (ડિબગિંગ માટે)",
    },
}


def pick_language() -> str:
    # The sidebar toggle drives UI updates because we render from T[...] each run.
    return st.sidebar.selectbox(
        label=TRANSLATIONS["en"]["language_label"],
        options=[("en", "English"), ("hi", "हिंदी"), ("gu", "ગુજરાતી")],
        format_func=lambda x: x[1],
        index=0,
    )[0]


LANG = pick_language()
T = TRANSLATIONS[LANG]


# -----------------------------
# Styling + palette
# -----------------------------

st.markdown(
    """
    <style>
      .stApp { background: #0E1117; }
      div[data-testid="stSidebar"] { background: #0B0E14; }
      .stMetric { border-radius: 12px; }
      .stMetricLabel, .stMetricValue { color: #E8E8E8; }
      .stSubheader { color: #E8E8E8; }
      .stText, .stMarkdown { color: #E8E8E8; }
    </style>
    """,
    unsafe_allow_html=True,
)

COLOR_SEQ = ["#0f4c75", "#3282b8", "#bbe1fa", "#00bcd4", "#1b4965", "#4aa3df"]


# -----------------------------
# MongoDB
# -----------------------------


@st.cache_resource(show_spinner=False)
def get_mongo_client(uri: str = "mongodb://localhost:27017/") -> MongoClient:
    """Cached MongoDB client to avoid creating thousands of connections."""

    return MongoClient(uri, serverSelectionTimeoutMS=3000)


def mongo_ping_ok(client: MongoClient) -> bool:
    try:
        client.admin.command("ping")
        return True
    except Exception:
        return False


def safe_docs_to_df(docs: List[Dict[str, Any]]) -> pd.DataFrame:
    if not docs:
        return pd.DataFrame()
    for d in docs:
        d.pop("_id", None)
    return pd.DataFrame(docs)


def pick_first_existing_column(df: pd.DataFrame, candidates: List[str]) -> Optional[str]:
    for c in candidates:
        if c in df.columns:
            return c
    return None


def to_numeric_sum(series: Optional[pd.Series]) -> float:
    if series is None or len(series) == 0:
        return 0.0
    return float(pd.to_numeric(series, errors="coerce").fillna(0).sum())


@st.cache_data(show_spinner=False)
def load_collection_as_df(db_name: str, collection_name: str, limit: int = 10000) -> pd.DataFrame:
    client = get_mongo_client("mongodb://localhost:27017/")
    coll = client[db_name][collection_name]
    docs = list(coll.find({}, limit=limit))
    return safe_docs_to_df(docs)


# -----------------------------
# Debug / schema checks
# -----------------------------


def debug_schema_if_missing(df: pd.DataFrame, expected: List[str], title: str, error_title: str) -> None:
    """Show missing-column diagnostics + required column preview.

    The dashboard should remain stable (never crash) even if expected columns differ.
    """

    if df.empty:
        return

    missing = [c for c in expected if c not in df.columns]
    if not missing:
        return

    # Required by user: show df.head(1) so they can see actual Mongo/PySpark output columns.
    st.info(error_title)
    st.write(f"{title}")
    st.write("Missing columns:", missing)
    st.write("Columns present:", list(df.columns))
    st.write("Preview (first row):")
    st.write(df.head(1))


# -----------------------------
# Charts
# -----------------------------


def build_funnel_chart(df: pd.DataFrame, lang: Dict[str, str]) -> Optional[Figure]:
    if df.empty:
        return None

    # PySpark output uses: sessions_with_view, sessions_with_add_to_cart, sessions_with_purchase
    view_col = pick_first_existing_column(df, [
        "view_count",
        "views",
        "view",
        "sessions_with_view",
        "sessions_with_views",
    ])
    cart_col = pick_first_existing_column(df, [
        "cart_count",
        "cart",
        "add_to_cart_count",
        "add_to_cart",
        "sessions_with_add_to_cart",
    ])
    purchase_col = pick_first_existing_column(df, [
        "purchase_count",
        "purchases",
        "purchase",
        "sessions_with_purchase",
    ])

    # PySpark pipeline writes: sessions_with_view, sessions_with_add_to_cart, sessions_with_purchase
    # We still keep the debugging contract, but we show missing fields for BOTH naming schemes.
    expected_spark = ["sessions_with_view", "sessions_with_add_to_cart", "sessions_with_purchase"]
    expected_alt = ["view_count", "cart_count", "purchase_count"]
    # For funnel, we should not block rendering if the alternate schema is missing.
    # We'll render only when at least one of the supported column naming schemes is available.
    supported_funnel_targets = expected_spark + expected_alt

    # First, check the PySpark-written schema (this should usually match).
    debug_schema_if_missing(
        df,
        expected=expected_spark,
        title=T["columns_debug_title"],
        error_title=T["error_expected_columns_missing"],
    )

    # Then, check alternative naming (only for visibility).
    debug_schema_if_missing(
        df,
        expected=expected_alt,
        title=T["columns_debug_title"],
        error_title=T["error_expected_columns_missing"],
    )

    # Render if we can find at least one supported naming scheme.
    # funnel requires all three stages, so we validate whichever naming scheme matched.
    if not ((view_col and cart_col and purchase_col)): 
        # Show a minimal preview to help user validate schema.
        if not df.empty:
            st.write("Funnel schema preview:")
            st.write(df.head(1))
        return None

    funnel_df = pd.DataFrame(
        [
            {"stage": lang["funnel_view"], "count": to_numeric_sum(df[view_col])},
            {"stage": lang["funnel_cart"], "count": to_numeric_sum(df[cart_col])},
            {"stage": lang["funnel_purchase"], "count": to_numeric_sum(df[purchase_col])},
        ]
    )

    fig = px.funnel(
        funnel_df,
        x="count",
        y="stage",
        title=lang["funnel_title"],
        orientation="h",
        color="stage",
        color_discrete_sequence=COLOR_SEQ,
    )

    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#E8E8E8"),
        title_font=dict(color="#E8E8E8"),
        margin=dict(l=20, r=20, t=60, b=20),
        showlegend=False,
    )
    fig.update_xaxes(showgrid=False, tickfont=dict(color="#E8E8E8"))
    fig.update_yaxes(showgrid=False, tickfont=dict(color="#E8E8E8"))

    return fig


def build_trending_bar_chart(df: pd.DataFrame, lang: Dict[str, str]) -> Tuple[Optional[Figure], pd.DataFrame]:
    if df.empty:
        return None, pd.DataFrame()

    product_col = pick_first_existing_column(df, ["product_id", "product", "productId"])
    category_col = pick_first_existing_column(df, ["category", "cat"])
    count_col = pick_first_existing_column(df, ["count", "purchase_count", "views", "metric_count"])

    debug_schema_if_missing(
        df,
        expected=["product_id", "category", "count"],
        title=T["columns_debug_title"],
        error_title=T["error_expected_columns_missing"],
    )

    if not (product_col and count_col):
        return None, df

    out = df.copy()

    if category_col and category_col in out.columns:
        out["product_label"] = out.apply(
            lambda r: f"{r.get(category_col, '')} • {r.get(product_col, '')}".strip(" •"), axis=1
        )
    else:
        out["product_label"] = out[product_col].astype(str)

    out["count_numeric"] = pd.to_numeric(out[count_col], errors="coerce").fillna(0)

    # Required: explicitly restrict to 10 and sort (highest at top)
    out = out.sort_values("count_numeric", ascending=False).nlargest(10, "count_numeric")

    fig = px.bar(
        out,
        x="count_numeric",
        y="product_label",
        orientation="h",
        title=lang["trending_title"],
        color="count_numeric",
        color_continuous_scale=["#0f4c75", "#3282b8", "#bbe1fa"],
    )

    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#E8E8E8"),
        title_font=dict(color="#E8E8E8"),
        margin=dict(l=20, r=20, t=60, b=20),
        showlegend=False,
        xaxis_title=lang["trending_x"],
        yaxis_title=lang["trending_y"],
    )

    fig.update_xaxes(showgrid=False, tickfont=dict(color="#E8E8E8"), title_font=dict(color="#E8E8E8"))
    fig.update_yaxes(showgrid=False, tickfont=dict(color="#E8E8E8"))

    # Table - top 10
    table_df = out.copy()
    # Normalize names
    if product_col != "product_id" and product_col in table_df.columns:
        table_df = table_df.rename(columns={product_col: "product_id"})
    if category_col and category_col in table_df.columns and category_col != "category":
        table_df = table_df.rename(columns={category_col: "category"})
    if count_col != "count" and count_col in table_df.columns:
        table_df = table_df.rename(columns={count_col: "count"})

    table_df["count"] = table_df.get("count", table_df["count_numeric"]).fillna(0)
    table_df = table_df[[c for c in ["product_id", "category", "count", "product_label"] if c in table_df.columns]]
    table_df = table_df.rename(columns={"product_label": "product"})

    return fig, table_df.reset_index(drop=True)


# -----------------------------
# Refresh
# -----------------------------

refresh_clicked = st.sidebar.button(T["refresh_button"], use_container_width=True)
if refresh_clicked:
    # Required: clear cache and rerun
    try:
        st.cache_data.clear()
    except Exception:
        pass
    try:
        st.cache_resource.clear()
    except Exception:
        pass
    st.rerun()


# -----------------------------
# Sidebar: About + KPIs + DB status
# -----------------------------

st.sidebar.markdown("---")
st.sidebar.subheader(T["about_section"])
st.sidebar.write(T["about"])

st.sidebar.markdown("---")
st.sidebar.subheader(T["sidebar_kpis"])

# DB status
mongo_ok = False
try:
    client = get_mongo_client("mongodb://localhost:27017/")
    mongo_ok = mongo_ping_ok(client)
except Exception:
    mongo_ok = False

# Load data (only if mongo reachable)
db_name = "analytics_db"
user_col = "user_session_metrics"
funnel_col = "conversion_funnel_metrics"
trending_col = "trending_products"

user_df = pd.DataFrame()
funnel_df_raw = pd.DataFrame()
trending_df_raw = pd.DataFrame()

if mongo_ok:
    with st.spinner("Loading data from MongoDB..."):
        user_df = load_collection_as_df(db_name, user_col, limit=10000)
        funnel_df_raw = load_collection_as_df(db_name, funnel_col, limit=10000)
        trending_df_raw = load_collection_as_df(db_name, trending_col, limit=10000)

# KPI calculations (collection 1)
kpi_users = 0
kpi_actions = 0
if not user_df.empty:
    user_id_col = pick_first_existing_column(user_df, ["user_id", "userId", "uid"])
    actions_col = pick_first_existing_column(
        user_df, ["total_actions", "actions", "totalActionCount", "total_action_count"]
    )
    if user_id_col:
        kpi_users = int(user_df[user_id_col].nunique())
    else:
        kpi_users = int(len(user_df))

    if actions_col:
        kpi_actions = int(to_numeric_sum(user_df[actions_col]))

# Sidebar metrics
st.sidebar.metric(label=T["kpi_db"], value="✅ " + (T["mongo_status_connected"] if mongo_ok else T["mongo_status_disconnected"]))
st.sidebar.metric(label=T["kpi_users"], value=f"{kpi_users:,}")
st.sidebar.metric(label=T["kpi_actions"], value=f"{kpi_actions:,}")
st.sidebar.caption(f"{T['kpi_last_refresh']}: {dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")


# -----------------------------
# Main header + tabs
# -----------------------------

st.title(T["app_name"])
st.caption(T["subtitle"])

if not mongo_ok:
    st.warning(T["mongo_status_disconnected"])
else:
    no_data = user_df.empty and funnel_df_raw.empty and trending_df_raw.empty
    if no_data:
        st.warning(T["empty_warning_run_pipeline"])
    else:
        tabs = st.tabs([T["visual_analytics"], T["raw_data_explorer"]])

        # -----------------------------
        # Tab 1: Visual Analytics
        # -----------------------------
        with tabs[0]:
            c_funnel, c_trending = st.columns(2, gap="large")

            with c_funnel:
                st.subheader(T["section_funnel"])
                if funnel_df_raw.empty:
                    st.warning(T["empty_warning_run_pipeline"])
                else:
                    fig_funnel = build_funnel_chart(funnel_df_raw, T)
                    if fig_funnel is None:
                        st.warning(T["error_expected_columns_missing"])
                    else:
                        st.plotly_chart(fig_funnel, use_container_width=True, config={"displayModeBar": False})

            with c_trending:
                st.subheader(T["section_trending"])
                if trending_df_raw.empty:
                    st.warning(T["empty_warning_run_pipeline"])
                else:
                    fig_trend, _table_df = build_trending_bar_chart(trending_df_raw, T)
                    if fig_trend is None:
                        st.warning(T["error_expected_columns_missing"])
                    else:
                        st.plotly_chart(fig_trend, use_container_width=True, config={"displayModeBar": False})

            st.markdown("---")
            st.write(
                "**Debugging tip:** If charts look empty, the dashboard automatically shows a schema preview with missing columns so you can verify column-name mismatches."
            )

        # -----------------------------
        # Tab 2: Raw Data Explorer
        # -----------------------------
        with tabs[1]:
            st.subheader("Mongo Collections (Preview)")

            t1, t2, t3 = st.tabs(["user_session_metrics", "conversion_funnel_metrics", "trending_products"])

            with t1:
                st.write(f"Rows: {len(user_df):,}")
                st.dataframe(user_df.head(50), use_container_width=True, hide_index=True)

            with t2:
                st.write(f"Rows: {len(funnel_df_raw):,}")
                st.dataframe(funnel_df_raw.head(50), use_container_width=True, hide_index=True)

            with t3:
                st.write(f"Rows: {len(trending_df_raw):,}")
                st.dataframe(trending_df_raw.head(50), use_container_width=True, hide_index=True)

            st.markdown("---")
            st.subheader(T["table_title"])

            if not trending_df_raw.empty:
                _fig, top_table = build_trending_bar_chart(trending_df_raw, T)
                if top_table is not None and not top_table.empty:
                    st.dataframe(top_table, use_container_width=True, hide_index=True, height=420)
                else:
                    st.warning(T["empty_warning_run_pipeline"])
            else:
                st.warning(T["empty_warning_run_pipeline"])

            st.caption(f"Last refreshed (local): {dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

